<?php

declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';
requireLogin('login.php');

$user = currentUser();
$pdo = Database::getInstance();
$mine = $pdo->prepare('SELECT n.id, n.title, n.status, n.is_anonymous, n.image, n.created_at, c.name AS category_name FROM news n LEFT JOIN categories c ON c.id = n.category_id WHERE n.author_id = :author ORDER BY n.created_at DESC');
$mine->execute([':author' => (int)$user['id']]);
$posts = $mine->fetchAll();
$flash = getFlash();
$siteName = getSetting('site_name', APP_NAME);
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>My Dashboard | <?= e($siteName) ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"></head><body class="bg-light"><main class="container-fluid"><div class="row"><aside class="col-lg-2 dashboard-sidebar p-3"><h4 class="text-white"><?= e($siteName) ?></h4><p class="text-white-50 small">Contributor dashboard</p><nav class="nav flex-column gap-1"><a class="active" href="dashboard.php">Dashboard</a><a href="submit.php">➕ Write News</a><a href="index.php">Public Site</a><a href="logout.php">Logout</a></nav></aside><section class="col-lg-10 p-4"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4"><div><h2>Welcome, <?= e((string)$user['username']) ?></h2><p class="text-muted mb-0">Track your news submissions and publishing status.</p></div><a href="submit.php" class="btn btn-primary">➕ Write New Story</a></div><?php if($flash): ?><div class="alert alert-<?= e((string)$flash['type']) ?>"><?= e((string)$flash['message']) ?></div><?php endif; ?><div class="row g-3 mb-4"><div class="col-sm-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Total submissions</small><div class="display-6 fw-bold"><?= count($posts) ?></div></div></div></div><div class="col-sm-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Pending review</small><div class="display-6 fw-bold text-warning"><?= count(array_filter($posts, fn($p) => $p['status'] === 'pending')) ?></div></div></div></div><div class="col-sm-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Published</small><div class="display-6 fw-bold text-success"><?= count(array_filter($posts, fn($p) => $p['status'] === 'published')) ?></div></div></div></div></div><div class="card border-0 shadow-sm"><div class="card-body"><h4 class="mb-3">My Submissions</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Story</th><th>Category</th><th>Status</th><th>Date</th></tr></thead><tbody><?php if(!$posts): ?><tr><td colspan="4" class="text-muted text-center py-4">You have not submitted any stories yet.</td></tr><?php endif; ?><?php foreach($posts as $post): ?><tr><td><?php if($post['image']): ?><img class="thumb me-2" src="<?= e((string)$post['image']) ?>" alt=""><?php endif; ?><a href="news.php?id=<?= (int)$post['id'] ?>"><?= e((string)$post['title']) ?></a></td><td><?= e((string)($post['category_name'] ?? 'General')) ?></td><td><span class="badge text-bg-secondary"><?= e((string)$post['status']) ?></span></td><td><?= e(date('M d, Y', strtotime((string)$post['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></section></div></main></body></html>
